version: '3.8'

services:
  app:
    ports:
      - "8081:8080"
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8082:8080"
  db:
    ports:
      - "5432:5432"
