-- Migration: Initial Schema
-- Created by: SolemnitySSO
-- Created on: 2023-12-26 04:52:00
-- Last Modified: 2023-12-31 22:50:00
-- Version: 0.10.0
-- Description: This migration creates the initial schema for the SolemnitySSO OAuth Server.

-- Create the Users table
CREATE TABLE IF NOT EXISTS Users (
    Id BINARY(16) PRIMARY KEY,
    Verified BOOLEAN,
    DisplayName VARCHAR(255),
    PrimaryEmail VARCHAR(255) NOT NULL UNIQUE,
    PrimaryPictureId BINARY(16),
    PrimaryLanguage VARCHAR(255),
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the User Pictures table
CREATE TABLE IF NOT EXISTS UserPictures (
    Id BINARY(16) PRIMARY KEY,
    PictureType VARCHAR(50),
    PictureUrl VARCHAR(255),
    UserId BINARY(16),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the User Emails table
CREATE TABLE IF NOT EXISTS UserEmails (
    Email VARCHAR(255) PRIMARY KEY,
    IsPrimary BOOLEAN,
    Verified BOOLEAN,
    UserId BINARY(16),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);

-- Create the OAuth Providers table
CREATE TABLE IF NOT EXISTS Providers (
    Id VARCHAR(255) PRIMARY KEY,
    ProviderName VARCHAR(255),
    ProviderId VARCHAR(255),
    Principal VARCHAR(255),
    UserId BINARY(16),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    UNIQUE (ProviderName, ProviderId),
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the Clients table
CREATE TABLE IF NOT EXISTS Clients (
    Id VARCHAR(255) PRIMARY KEY,
    ClientSecret VARCHAR(255),
    RedirectUris TEXT,
    Scopes TEXT,
    GrantTypes TEXT,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the Access Tokens table
CREATE TABLE IF NOT EXISTS AccessTokens (
    TokenSignature VARCHAR(255) PRIMARY KEY,
    ClientId VARCHAR(255),
    TokenData BLOB,
    TokenExpiry TIMESTAMP,
    FOREIGN KEY (ClientId) REFERENCES Clients(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the Refresh Tokens table
CREATE TABLE IF NOT EXISTS RefreshTokens (
    TokenSignature VARCHAR(255) PRIMARY KEY,
    ClientId VARCHAR(255),
    TokenData BLOB,
    TokenExpiry TIMESTAMP,
    FOREIGN KEY (ClientId) REFERENCES Clients(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the Auth Codes table
CREATE TABLE IF NOT EXISTS AuthCodes (
    CodeSignature VARCHAR(255) PRIMARY KEY,
    ClientId VARCHAR(255),
    CodeData BLOB,
    CodeExpiry TIMESTAMP,
    FOREIGN KEY (ClientId) REFERENCES Clients(Id) ON DELETE CASCADE
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the User Consents table
CREATE TABLE IF NOT EXISTS UserConsents (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId BINARY(16),
    ClientId VARCHAR(255),
    Scopes TEXT,
    FOREIGN KEY (ClientId) REFERENCES Clients(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the Scopes table
CREATE TABLE IF NOT EXISTS Scopes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ScopeName VARCHAR(255) UNIQUE,
    ScopeDescription TEXT,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


